package com.rollingstar.cottages.model;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "payment_transactions")
public class PaymentTransaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Unique reference token generated by our system (e.g., COT-TX-20260626-001)
    @Column(name = "tx_reference", unique = true, nullable = false)
    private String txReference;

    @Column(name = "amount", nullable = false)
    private BigDecimal amount;

    @Column(name = "currency", nullable = false)
    private String currency;

    @Column(name = "customer_phone")
    private String customerPhone;

    // Transaction lifecycle flags: PENDING, SUCCESSFUL, FAILED
    @Column(name = "status", nullable = false)
    private String status;

    // Hybrid Type Tracker: CASH, MOBILE_MONEY, CARD
    @Column(name = "payment_method", nullable = false)
    private String paymentMethod;

    // Reference ID sent back by MTN/Airtel/FinTech Gateway after payment complete
    @Column(name = "external_gateway_id")
    private String externalGatewayId;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // Default Constructor (Strictly required by JPA)
    public PaymentTransaction() {}

    // Overloaded Constructor for easy instantiation when checkout begins
    public PaymentTransaction(String txReference, BigDecimal amount, String currency, String customerPhone, String status, String paymentMethod) {
        this.txReference = txReference;
        this.amount = amount;
        this.currency = currency;
        this.customerPhone = customerPhone;
        this.status = status;
        this.paymentMethod = paymentMethod.toUpperCase();
        this.createdAt = LocalDateTime.now();
    }

    // Automatically refresh the updated_at column before updating the database row
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    // --- GETTERS AND SETTERS ---
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getTxReference() { return txReference; }
    public void setTxReference(String txReference) { this.txReference = txReference; }

    public BigDecimal getAmount() { return amount; }
    public void setAmount(BigDecimal amount) { this.amount = amount; }

    public String getCurrency() { return currency; }
    public void setCurrency(String currency) { this.currency = currency; }

    public String getCustomerPhone() { return customerPhone; }
    public void setCustomerPhone(String customerPhone) { this.customerPhone = customerPhone; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public String getPaymentMethod() { return paymentMethod; }
    public void setPaymentMethod(String paymentMethod) { this.paymentMethod = paymentMethod != null ? paymentMethod.toUpperCase() : null; }

    public String getExternalGatewayId() { return externalGatewayId; }
    public void setExternalGatewayId(String externalGatewayId) { this.externalGatewayId = externalGatewayId; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
}